import { faPerson } from '@fortawesome/free-solid-svg-icons';
import { WaterfallCategory } from '../../../../types/waterfall-types';
import {
  ATTR_A11Y_CONTAINER_MESSAGE,
  ATTR_A11Y_CONTAINER_ROLE,
  ATTR_A11Y_CONTAINER_ROLE_DESCRIPTION_MESSAGE,
  ATTR_A11Y_ENABLED,
  ATTR_A11Y_FIRST_SLIDE_MESSAGE,
  ATTR_A11Y_ID,
  ATTR_A11Y_ITEM_ROLE_DESCRIPTION_MESSAGE,
  ATTR_A11Y_LAST_SLIDE_MESSAGE,
  ATTR_A11Y_NEXT_SLIDE_MESSAGE,
  ATTR_A11Y_NOTIFICATION_CLASS,
  ATTR_A11Y_PAGINATION_BULLET_MESSAGE,
  ATTR_A11Y_PREV_SLIDE_MESSAGE,
  ATTR_A11Y_SCROLL_ON_FOCUS,
  ATTR_A11Y_SLIDE_LABEL_MESSAGE,
  ATTR_A11Y_SLIDE_ROLE,
} from 'well-waterfall/src/lib/attributes';

export default function a11yConfig() {
  let config: WaterfallCategory = {
    name: 'Accessibility (a11y)',
    id: 'accessibility',
    description: 'Set a11y messages, roles, and tags',
    summary: 'Set a11y messages, roles, and tags',
    icon: faPerson,
    items: [
      {
        name: 'Container Message',
        attr: ATTR_A11Y_CONTAINER_MESSAGE,
        swiperDefault: '',
        description: 'Message for screen readers for outer swiper container',
        value: '',
        tested: false,
        type: 'string',
      },
      {
        name: 'Container Role',
        attr: ATTR_A11Y_CONTAINER_ROLE,
        swiperDefault: '',
        description: 'Value of the "role" attribute to be set on the swiper container',
        value: '',
        tested: false,
        type: 'string',
      },
      {
        name: 'Container Role Description Message',
        attr: ATTR_A11Y_CONTAINER_ROLE_DESCRIPTION_MESSAGE,
        swiperDefault: '',
        description: 'Message for screen readers describing the role of outer swiper container',
        value: '',
        tested: false,
        type: 'string',
      },
      {
        name: 'Enabled',
        attr: ATTR_A11Y_ENABLED,
        swiperDefault: '',
        description: 'Enables A11y',
        value: '',
        type: 'boolean',
        tested: false,
      },
      {
        name: 'First Slide Message',
        attr: ATTR_A11Y_FIRST_SLIDE_MESSAGE,
        swiperDefault: 'This is the first slide',
        description: 'Message for screen readers for previous button when swiper is on first slide',
        value: '',
        tested: false,
        type: 'string',
      },
      {
        name: 'Id',
        attr: ATTR_A11Y_ID,
        swiperDefault: '',
        description: 'Value of id attribute to be set on swiper-wrapper. If null will be generated automatically',
        value: '',
        tested: false,
        type: 'string',
      },
      {
        name: 'Item Role Description Message',
        attr: ATTR_A11Y_ITEM_ROLE_DESCRIPTION_MESSAGE,
        swiperDefault: '',
        description: 'Message for screen readers describing the role of slide element',
        value: '',
        tested: false,
        type: 'string',
      },
      {
        name: 'Last Slide Message',
        attr: ATTR_A11Y_LAST_SLIDE_MESSAGE,
        swiperDefault: 'This is the last slide',
        description: 'Message for screen readers for next button when swiper is on last slide',
        value: '',
        tested: false,
        type: 'string',
      },
      {
        name: 'Next Slide Message',
        attr: ATTR_A11Y_NEXT_SLIDE_MESSAGE,
        swiperDefault: 'Next Slide',
        value: '',
        description: 'Message for screen readers for next button',
        tested: false,
        type: 'string',
      },
      {
        name: 'Notification Class',
        attr: ATTR_A11Y_NOTIFICATION_CLASS,
        swiperDefault: 'swiper-notification',
        description: 'CSS class name of A11y notification',
        value: '',
        tested: false,
        type: 'string',
      },
      {
        name: 'Pagination Bullet Message',
        attr: ATTR_A11Y_PAGINATION_BULLET_MESSAGE,
        swiperDefault: 'Go to slide {{index}}',
        description: 'Message for screen readers for single pagination bullet',
        value: '',
        tested: false,
        type: 'string',
      },
      {
        name: 'Prev Slide Message',
        attr: ATTR_A11Y_PREV_SLIDE_MESSAGE,
        swiperDefault: 'Previous Slide',
        description: 'Message for screen readers for previous button',
        value: '',
        tested: false,
        type: 'string',
      },
      {
        name: 'Scroll on Focus',
        attr: ATTR_A11Y_SCROLL_ON_FOCUS,
        swiperDefault: 'true',
        description: 'Enables scrolling to the slide that has been focused',
        value: '',
        type: 'boolean',
        tested: false,
      },
      {
        name: 'Slide Label Message',
        attr: ATTR_A11Y_SLIDE_LABEL_MESSAGE,
        swiperDefault: '{{index}} / {{slidesLength}}',
        description: 'Message for screen readers describing the label of slide element',
        value: '',
        tested: false,
        type: 'string',
      },
      {
        name: 'Slide Role',
        attr: ATTR_A11Y_SLIDE_ROLE,
        swiperDefault: 'group',
        description: 'Value of swiper slide role attribute',
        value: '',
        tested: false,
        type: 'string',
      },
    ],
  };
  return config;
}
